# Generated by Django 3.2.8 on 2021-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_alter_myfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='uploaded_by',
            field=models.EmailField(max_length=254),
        ),
    ]
