# Generated by Django 3.2.8 on 2021-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0003_alter_myfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='files/%y/%m/'),
        ),
    ]
