# Generated by Django 3.2.8 on 2021-10-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0004_alter_myfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='files/%Y/%b/'),
        ),
    ]
